version: '3'

services:
  app:
    build: .
    command: yarn start
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app

  postgres:
    build: .
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: docker

  mongo:
    ports:
      - '27017:27017'
    restart: always

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
